---
- hosts: ios
  gather_facts: no
  
  environment:
    GIT_SSH_OPTS: “-o StrictHostKeyChecking=no ”
    GIT_KEY: “{{ secret_key }}”  
  
  tasks:
  - name: DISPLAY THE INJECTED EXTRA VAR
    debug:
      var: secret_key
      
  roles:
  - role: backup_manager
    function: backup
    backup_manager_git_key_file: "{{ secret_key }}"
    
