---
- hosts: ios
  gather_facts: no
  
  tasks:
  - name: DISPLAY THE INJECTED EXTRA VAR
    debug:
      var: secret_key
      
  roles:
  - role: backup_manager
    function: backup
    backup_manager_git_deploy_key: "{{ secret_key }}"
    
