---
- name: DEMO AN INTERACTIVE PRIVATE KEY
  hosts: ios
  gather_facts: true
  tasks:
  
    - name: git pull
      include_role:
        name: ansible-git
        tasks_from: pull  
  
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
      register: config_output

    - name: move backup to repo
      copy:
        src: "{{config_output.backup_path}}"
        dest: "ansible_network_backups/{{inventory_hostname}}.config"  

    - name: git push
      include_role:
        name: ansible-git
        tasks_from: push
