---
- name: RESTORE CONFIGURATION
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
  
  - name: git pull
    include_role:
      name: ansible-git
      tasks_from: pull
      
    - name: COPY RUNNING CONFIG TO ROUTER
      command: scp ansible_network_backups/{{inventory_hostname}}.config {{inventory_hostname}}:/{{inventory_hostname}}.config

    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.config force
