---
- hosts: ios
  gather_facts: no


  vars:
  
    dns_servers:
      - ip name-server 8.8.8.8
      - ip name-server 8.8.4.4
      
      

  tasks:
  
  - name: "GET CONFIG"
    ios_command:
      commands:
        - "show running-config full | include ip name-server"
    register: get_config
    when: 

  - debug: var=get_config.stdout_lines

  - name: RUN 'Set DNS'
    with_items: "{{ dns_servers }}"
    ios_config:
      lines:
        - "{{ item }}"
    register: set_dns

  - name: RUN 'Remove DNS'
    when: "(get_config.stdout_lines[0] != '') and (item not in dns_servers)"
    with_items: "{{ get_config.stdout_lines[0] }}"
    register: remove_dns
    ios_config:
      lines:
        - "no {{ item }}"

  - name: CHECK CHANGE - dns
    when: set_dns.changed or remove_dns.changed
    set_fact: configured=true
  
  - debug: var=configured
