---
- name: pyats testing
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - parse_genie

  tasks:

  - name: show version
    ios_command:
      commands:
        - show version
    register: version


  - name: Debug Genie Filter
    debug:
      msg: "{{ version['stdout'][0] | parse_genie(command='show version', os='ios') }}"
      verbosity: 2

  - name: Set Fact Genie Filter
    set_fact: 
      pyats_version: "{{ version['stdout'][0] | parse_genie(command='show version', os='ios') }}"

  - name: Debug Pyats facts
    debug:
     var: pyats_version.version.rtr_type
