---
- name: create ticket with notes
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - parse_genie

  tasks:
  - name: include vars
    include_vars: incident_vars.yml

  - name: show version
    ios_command:
      commands:
        - show version
    register: version


  - name: Debug Genie Filter
    debug:
      msg: "{{ version['stdout'][0] | parse_genie(command='show version', os='ios') }}"
    delegate_to: localhost
