---
- name: create ticket with notes
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - parse_genie

  tasks:
  - name: include vars
    include_vars: incident_vars.yml

  - name: show version
    ios_command:
      commands:
        - show version
    register: version


  - name: Debug Genie Filter
    debug:
      msg: "{{ version.stdout | parse_genie(command='show version', os='ios') }}"
    delegate_to: localhost






  - meta: end_play

  - name: Create an incident
    snow_record:
      state: present
      table: incident
      username: "{{ SN_USERNAME }}"
      password: "{{ SN_PASSWORD }}"
      instance: "{{ SN_INSTANCE }}"
      data:
        priority: "{{ priority}}"
        u_device_up_time: "{{ system_facts.uptime }}"
        u_ios_version: "{{ system_facts.version }}"
        short_description: "This ticket was created by Ansible"
    register: new_incident

  - debug: var=new_incident.record
