---
- name: pyats testing
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - parse_genie

  tasks:

  - name: show version
    ios_command:
      commands:
        - show interfaces
    register: interfaces


  - name: Debug Genie Filter
    debug:
      msg: "{{ interfaces['stdout'][0] | parse_genie(command='show interfaces', os='ios') }}"
      verbosity: 2

  - name: Set Fact Genie Filter
    set_fact: 
      pyats_interfaces: "{{ interfaces['stdout'][0] | parse_genie(command='show interfaces', os='ios') }}"

  - name: Debug Pyats facts
    debug:
     var: pyats_interfaces
