---
- name: create ticket with notes
  hosts: ios
  gather_facts: no
  connection: network_cli

  tasks:
  - name: include vars
    include_vars: incident_vars.yml

  - name: Create an incident
    snow_record:
      state: present
      table: incident
      username: "{{ SN_USERNAME }}"
      password: "{{ SN_PASSWORD }}"
      instance: "{{ SN_INSTANCE }}"
      data:
        priority: "{{ priority}}"
        short_description: "This ticket was created by Zabbix"
    register: new_incident

  - debug: var=new_incident.record.number
